
export const SET_POSITION = 'SET_POSITION'
export const SAVE_PAGE = 'SAVE_PAGE'
export const SET_LOCATION = 'SET_LOCATION'
export const SET_ADDRESSLIST = 'SET_ADDRESSLIST'
export const SAVE_SEARCHKEY = 'SAVE_SEARCHKEY'

